apiVersion: apps/v1
kind: Deployment
metadata:
  name: adeline
  namespace: adeline
spec:
  selector:
    matchLabels:
      app: adeline
  replicas: 1
  template:
    metadata:
      labels:
        app: adeline
    spec:
      containers:
      - name: adeline
        image: ghcr.io/andrewkreuzer/adeline:main-68727d23-2807204768 # {"$imagepolicy": "flux-system:adeline"}
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 10
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: /tmp/adeline/
            name: logs
        volumes:
          - name: logs
            emptyDir: {}
        env:
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack
              key: app-token
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack
              key: bot-token
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              name: slack
              key: signing-secret
        - name: MONGODB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: mongodb-adeline
              key: connection-string
